title: Resume
description: A one page resume for Aura B
sitename: Aura Barrera
baseurl: '/resume'
twitter_username:     AuraiBarrera
github_username:      aura-b
linkedin_username:    aurabarrera
facebook_username:    auraibarrera
#dribbble_username:
sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  - features
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.txt
  - CNAME
